# Variational assembly of the shear-thinning drop model.
#
# This implements the model as stated in the "Model summary" of the derivation page
# *Shear-Thinning Drops*: a damped Lagrangian system in the interior displacement
# coordinates, with the surface amplitude determined by the kinematic condition.
#
# WHY THE COORDINATES ARE DISPLACEMENTS, not the stream function itself. The
# summary's state is (zeta_l, psi_l), but psi_l is a VELOCITY-like quantity -- the
# kinetic energy is quadratic in psi, and the kinematic condition reads
# psi_l(1) = d(zeta_l)/dt. A Lagrangian needs (q, qdot), so the coordinate is the
# interior DISPLACEMENT chi_l with
#
#     psi_l = d(chi_l)/dt ,      zeta_l = chi_l(1) ,
#
# the second following from integrating the kinematic condition. Everything is then
# in chi alone, and the surface amplitude is its boundary trace -- which is also the
# resolution of the coordinate-count question: there is no independent equation for
# zeta_l, because zeta_l is not an independent coordinate.
#
# With chi_l(x,t) = sum_k a_k(t) phi_k(x) on a Ritz basis satisfying regularity,
#
#     M ddot(a) + K dot(a) + G a = Q ,
#
#     M_ab = int u^(a) . u^(b) dV                     (kinetic / added mass)
#     K_ab = Oh int 2 eta e^(a):e^(b) dV              (dissipation)
#     G_ab = (4pi/(2l+1)) (l-1)(l+2) phi_a(1) phi_b(1)  (surface energy)
#
# G is RANK ONE for a single mode, because the surface energy sees the interior only
# through the boundary trace. That is a structural feature worth knowing: it means
# the stiffness cannot resolve interior structure, and only the trace phi_a(1)
# matters to it.
#
# All three are assembled by ONE derivative of the velocity -- no stress divergence,
# no curl, no fourth-order operator -- which is the point of the variational form.
# Strain components are evaluated from their analytic modal expressions, so there is
# no finite-difference error anywhere in the assembly.

using LinearAlgebra
# Gauss-Legendre nodes come from the package's own `integrals.jl` rather than a new
# dependency -- it is already used by the contact quadrature.

"""
    RitzBasis(l, K)

Radial trial functions for mode `l`: `phi_k(x) = x^(l+1+2(k-1))`, `k = 1..K`.

The factor `x^(l+1)` builds in regularity at the origin, which is what the model
requires of `psi_l`, so no boundary condition has to be imposed there. `phi_1` is
the potential-flow profile, so `K = 1` reproduces the inviscid limit exactly and
larger `K` adds interior structure. Even increments keep every member regular.
"""
struct RitzBasis
    l::Int
    K::Int
end

npow(b::RitzBasis, k::Int) = b.l + 1 + 2 * (k - 1)
phi(b::RitzBasis, k::Int, x::Real) = x^npow(b, k)
dphi(b::RitzBasis, k::Int, x::Real) = (n = npow(b, k); n * x^(n - 1))
d2phi(b::RitzBasis, k::Int, x::Real) = (n = npow(b, k); n * (n - 1) * x^(n - 2))

"""Legendre `P_l(mu)`, and the theta-derivatives the strain components need."""
function legendre_angular(l::Int, mu::Float64)
    p0, p1 = 1.0, mu
    if l == 0
        P, dPdmu = 1.0, 0.0
    elseif l == 1
        P, dPdmu = mu, 1.0
    else
        for n in 1:(l - 1)
            p0, p1 = p1, ((2n + 1) * mu * p1 - n * p0) / (n + 1)
        end
        P = p1
        dPdmu = l * (mu * p1 - p0) / (mu^2 - 1)
    end
    # Legendre's equation supplies the second derivative without a second recurrence
    d2Pdmu = (2mu * dPdmu - l * (l + 1) * P) / (1 - mu^2)
    s = sqrt(max(1 - mu^2, 0.0))
    dPdth = -s * dPdmu                        # d/dtheta
    d2Pdth = -mu * dPdmu + s^2 * d2Pdmu       # d2/dtheta2
    (P = P, dPdth = dPdth, d2Pdth = d2Pdth, sinth = s, mu = mu)
end

"""
Strain and velocity components of the field generated by `psi = f(x) C_l(theta)`,
from their analytic modal forms. Returns `(u_r, u_th, e_rr, e_tt, e_pp, e_rt)`.
"""
function modal_field(l::Int, f::Real, df::Real, d2f::Real, x::Real, A)
    L = l * (l + 1)
    u_r = f / x^2 * A.P
    u_th = df / (x * L) * A.dPdth
    e_rr = (df / x^2 - 2f / x^3) * A.P
    e_tt = df / (x^2 * L) * A.d2Pdth + f / x^3 * A.P
    cot_th = A.sinth > 1e-12 ? A.mu / A.sinth : 0.0
    e_pp = f / x^3 * A.P + df / (x^2 * L) * cot_th * A.dPdth
    T_op = d2f - 2df / x + L * f / x^2          # the tangential-stress operator
    e_rt = T_op / (2 * x * L) * A.dPdth
    (u_r, u_th, e_rr, e_tt, e_pp, e_rt)
end

"""
    assemble(b::RitzBasis, Oh; eta = (x, mu) -> 1.0, nx = 40, nmu = 40)

The three matrices of the variational statement, for one surface mode.

`eta` is the viscosity field in units of the zero-shear plateau, evaluated at
`(x, mu)`. For a Newtonian fluid it is `1`; for a generalized Newtonian one it is
`eta(gammadot)` on the current state, which makes `K` state-dependent.
"""
function assemble(b::RitzBasis, Oh::Real; eta = (x, mu) -> 1.0,
                  nx::Int = 40, nmu::Int = 40)
    l, K = b.l, b.K
    xs, wxs = gauss_legendre_nodes(nx, 0.0, 1.0)
    mus, wmus = gauss_legendre_nodes(nmu, -1.0, 1.0)
    M = zeros(K, K)
    Kd = zeros(K, K)
    for (x, wx) in zip(xs, wxs), (mu, wmu) in zip(mus, wmus)
        A = legendre_angular(l, mu)
        w = wx * wmu * 2pi * x^2                     # dV = 2 pi x^2 dx dmu
        ev = eta(x, mu)
        F = ntuple(k -> modal_field(l, phi(b, k, x), dphi(b, k, x),
                                    d2phi(b, k, x), x, A), K)
        for a in 1:K, c in a:K
            Fa, Fc = F[a], F[c]
            M[a, c] += w * (Fa[1] * Fc[1] + Fa[2] * Fc[2])
            Kd[a, c] += w * 2 * ev * (Fa[3] * Fc[3] + Fa[4] * Fc[4] +
                                      Fa[5] * Fc[5] + 2 * Fa[6] * Fc[6])
        end
    end
    for a in 1:K, c in 1:a-1        # both forms are Hessians, hence symmetric
        M[a, c] = M[c, a]; Kd[a, c] = Kd[c, a]
    end
    Kd .*= Oh
    # surface energy: rank one, seeing the interior only through the trace at x = 1
    tr = [phi(b, k, 1.0) for k in 1:K]
    G = (4pi / (2l + 1)) * (l - 1) * (l + 2) * (tr * tr')
    (M = M, C = Kd, G = G)
end

"""
    decay_rates(b::RitzBasis, Oh; kwargs...) -> Vector{ComplexF64}

Returns `(sigma, cond_M)`: roots of the quadratic eigenvalue problem `(sigma^2 M - sigma C + G) a = 0`,
i.e. the free-decay rates of mode `l` for `chi ~ exp(-sigma t)`.

Linearised to a standard generalized eigenproblem of twice the size. The physical
root is the one with the smallest real part -- the least damped.
"""
function decay_rates(b::RitzBasis, Oh::Real; kwargs...)
    F = assemble(b, Oh; kwargs...)
    K = b.K
    # WHITEN by the Cholesky factor of M before linearising. The monomial trial
    # functions are Vandermonde-like, so M's condition number grows fast with K and
    # the raw pencil returns spurious near-zero roots: at K = 8 omega^2 collapses to
    # 1e-9 and lambda halves, silently, while K = 5 is accurate to 1e-11. Whitening
    # moves the usable range out; it does not make the basis good, and `cond_M` is
    # returned so a caller can see when it has run out of room.
    Lc = cholesky(Symmetric(F.M)).L
    Ci = Lc \ (F.C / Lc')
    Gi = Lc \ (F.G / Lc')
    # [sigma^2 I - sigma Ci + Gi] y = 0  linearised:
    Abig = [Ci  -Gi; Matrix(I, K, K)  zeros(K, K)]
    Bbig = Matrix(I, 2K, 2K)
    (sigma = eigvals(Abig, Bbig), cond_M = cond(F.M))
end

"""
    dominant_pair(b::RitzBasis, Oh; kwargs...) -> (lambda, omega2)

The least-damped root pair, in the convention the Newtonian literature uses:
`zeta.. + 2 lambda zeta. + omega^2 zeta = 0`, returning `(lambda, omega^2)`.
Comparable directly against `reid_lambda_omega2`.

Note which `omega^2` this is. For that oscillator the roots are
`sigma = lambda +- i sqrt(omega^2 - lambda^2)`, so by Vieta `omega^2` is their
PRODUCT, `|sigma|^2` -- not `Im(sigma)^2`, which is the damped frequency
`omega^2 - lambda^2`. Reporting the latter leaves a discrepancy against Reid of
exactly `lambda^2/omega^2` that does not shrink as the basis is refined: a plateau
at `6.1e-3` for `Oh = 0.05` and `1.6e-1` for `Oh = 0.3`, while `lambda` itself was
converging to machine precision. A convergence study is what exposes a convention
error of this kind, because a wrong convention converges to the wrong number.
"""
function dominant_pair(b::RitzBasis, Oh::Real; kwargs...)
    R = decay_rates(b, Oh; kwargs...)
    σ = R.sigma
    finite = filter(s -> isfinite(s) && real(s) > 1e-12, σ)
    length(finite) < 2 && return (NaN, NaN)
    # VIETA ON THE TWO SLOWEST ROOTS, which is what lambda and omega^2 are. For an
    # underdamped mode those two are a conjugate pair and this reduces to
    # (Re sigma, |sigma|^2); above the critical Ohnesorge the pair goes REAL and the
    # conjugate reading breaks -- at Oh = 1, l = 2 it is wrong by 64%, and no amount
    # of basis refinement helps, because the two roots are then different numbers.
    # Taking the two slowest and applying Vieta covers both regimes.
    idx = partialsortperm(real.(finite), 1:2)
    s1, s2 = finite[idx[1]], finite[idx[2]]
    (real(s1 + s2) / 2, real(s1 * s2))
end

# ---------------------------------------------------------------------------
# Multi-mode assembly, which is where shear thinning actually bites.
#
# For a constant viscosity the modes do not talk to each other: eta has only its
# l = 0 harmonic, the Gaunt coefficient is a delta, and every block off the
# diagonal vanishes. That is why the single-mode assembly above is enough for the
# Newtonian case. A shear-thinning fluid destroys it: eta = eta(gammadot) inherits
# the angular structure of the strain field, its harmonics k >= 1 are non-zero, and
# the dissipation form acquires off-diagonal blocks. Those blocks ARE the physics
# of the shear-thinning problem, so the assembly has to carry them.
#
# gammadot is computed from the WHOLE field, never mode by mode: the strain tensor
# superposes over modes but its invariant does not, so there is no such thing as one
# mode's shear rate once more than one is active.

"""
    ModalBasis(ls, K)

Radial trial functions `K` per surface mode, over the modes `ls` (e.g. `2:M`).
Degrees of freedom are ordered mode-major: `(l, k) -> (i-1)*K + k` for the `i`-th
mode in `ls`.
"""
struct ModalBasis
    ls::Vector{Int}
    K::Int
end
ModalBasis(ls, K::Int) = ModalBasis(collect(ls), K)
ndof(b::ModalBasis) = length(b.ls) * b.K
dofindex(b::ModalBasis, i::Int, k::Int) = (i - 1) * b.K + k

"""
    strain_at(b::ModalBasis, x, mu) -> Matrix

The six field components of every degree of freedom at one quadrature point, as a
`ndof x 6` array in the order `(u_r, u_th, e_rr, e_tt, e_pp, e_rt)`. Assembling any
of the quadratic forms is then a contraction over rows.
"""
function strain_at(b::ModalBasis, x::Float64, mu::Float64)
    F = zeros(ndof(b), 6)
    for (i, l) in enumerate(b.ls)
        A = legendre_angular(l, mu)
        rb = RitzBasis(l, b.K)
        for k in 1:b.K
            f, df, d2f = phi(rb, k, x), dphi(rb, k, x), d2phi(rb, k, x)
            F[dofindex(b, i, k), :] .= modal_field(l, f, df, d2f, x, A)
        end
    end
    F
end

"""Full double contraction `e:e` of a strain given as `(e_rr, e_tt, e_pp, e_rt)`."""
ddot_strain(a, c) = a[3]*c[3] + a[4]*c[4] + a[5]*c[5] + 2*a[6]*c[6]

"""
    shear_rate(b::ModalBasis, a, x, mu) -> Float64

`gammadot = sqrt(2 e:e)` of the superposed field with velocity amplitudes `a`.
Built from the summed tensor, not from a per-mode sum of invariants.
"""
function shear_rate(b::ModalBasis, a::AbstractVector, x::Float64, mu::Float64)
    F = strain_at(b, x, mu)
    e = zeros(6)
    for d in 1:ndof(b), c in 1:6
        e[c] += a[d] * F[d, c]
    end
    sqrt(max(2 * ddot_strain(e, e), 0.0))
end

"""
    assemble_coupled(b::ModalBasis, Oh; eta = (x, mu) -> 1.0, nx = 40, nmu = 48)

The three forms over all retained modes. `eta` is the viscosity in units of the
zero-shear plateau, as a function of position -- for a shear-thinning fluid it is
`eta(shear_rate(...))` on the current state, which is what makes `C` couple modes.
"""
function assemble_coupled(b::ModalBasis, Oh::Real; eta = (x, mu) -> 1.0,
                          nx::Int = 40, nmu::Int = 48)
    N = ndof(b)
    xs, wxs = gauss_legendre_nodes(nx, 0.0, 1.0)
    mus, wmus = gauss_legendre_nodes(nmu, -1.0, 1.0)
    Mm, Cm = zeros(N, N), zeros(N, N)
    for (x, wx) in zip(xs, wxs), (mu, wmu) in zip(mus, wmus)
        F = strain_at(b, x, mu)
        w = wx * wmu * 2pi * x^2
        ev = eta(x, mu)
        for p in 1:N, q in p:N
            Mm[p, q] += w * (F[p,1]*F[q,1] + F[p,2]*F[q,2])
            Cm[p, q] += w * 2 * ev * ddot_strain(view(F, p, :), view(F, q, :))
        end
    end
    for p in 1:N, q in 1:p-1
        Mm[p, q] = Mm[q, p]; Cm[p, q] = Cm[q, p]
    end
    Cm .*= Oh
    Gm = zeros(N, N)
    for (i, l) in enumerate(b.ls)
        rb = RitzBasis(l, b.K)
        tr = [phi(rb, k, 1.0) for k in 1:b.K]
        blk = (4pi / (2l + 1)) * (l - 1) * (l + 2) * (tr * tr')
        rng = dofindex(b, i, 1):dofindex(b, i, b.K)
        Gm[rng, rng] .= blk
    end
    (M = Mm, C = Cm, G = Gm)
end

"""
    block_norm(b::ModalBasis, A, i, j) -> Float64

Largest entry of the `(i, j)` mode block of `A`. The measure of whether modes
`b.ls[i]` and `b.ls[j]` are coupled.
"""
function block_norm(b::ModalBasis, A::AbstractMatrix, i::Int, j::Int)
    ri = dofindex(b, i, 1):dofindex(b, i, b.K)
    rj = dofindex(b, j, 1):dofindex(b, j, b.K)
    maximum(abs, view(A, ri, rj))
end

"""
    carreau(gammadot; eta_inf_ratio, lambda_c, a, n) -> Float64

Carreau-Yasuda viscosity in units of the zero-shear plateau. `n < 1` is
shear-thinning; `eta_inf_ratio` is the infinite-shear plateau, which (H2) requires
to be strictly positive.
"""
function carreau(gd::Real; eta_inf_ratio::Real = 0.01, lambda_c::Real = 1.0,
                 a::Real = 2.0, n::Real = 0.5)
    eta_inf_ratio + (1 - eta_inf_ratio) * (1 + (lambda_c * gd)^a)^((n - 1) / a)
end
