# Variational assembly of the shear-thinning drop model.
#
# This implements the model as stated in the "Model summary" of the derivation page
# *Shear-Thinning Drops*: a damped Lagrangian system in the interior displacement
# coordinates, with the surface amplitude determined by the kinematic condition.
#
# WHY THE COORDINATES ARE DISPLACEMENTS, not the stream function itself. The
# summary's state is (zeta_l, psi_l), but psi_l is a VELOCITY-like quantity -- the
# kinetic energy is quadratic in psi, and the kinematic condition reads
# psi_l(1) = d(zeta_l)/dt. A Lagrangian needs (q, qdot), so the coordinate is the
# interior DISPLACEMENT chi_l with
#
#     psi_l = d(chi_l)/dt ,      zeta_l = chi_l(1) ,
#
# the second following from integrating the kinematic condition. Everything is then
# in chi alone, and the surface amplitude is its boundary trace -- which is also the
# resolution of the coordinate-count question: there is no independent equation for
# zeta_l, because zeta_l is not an independent coordinate.
#
# With chi_l(x,t) = sum_k a_k(t) phi_k(x) on a Ritz basis satisfying regularity,
#
#     M ddot(a) + K dot(a) + G a = Q ,
#
#     M_ab = int u^(a) . u^(b) dV                     (kinetic / added mass)
#     K_ab = Oh int 2 eta e^(a):e^(b) dV              (dissipation)
#     G_ab = (4pi/(2l+1)) (l-1)(l+2) phi_a(1) phi_b(1)  (surface energy)
#
# G is RANK ONE for a single mode, because the surface energy sees the interior only
# through the boundary trace. That is a structural feature worth knowing: it means
# the stiffness cannot resolve interior structure, and only the trace phi_a(1)
# matters to it.
#
# All three are assembled by ONE derivative of the velocity -- no stress divergence,
# no curl, no fourth-order operator -- which is the point of the variational form.
# Strain components are evaluated from their analytic modal expressions, so there is
# no finite-difference error anywhere in the assembly.

using LinearAlgebra
# Gauss-Legendre nodes come from the package's own `integrals.jl` rather than a new
# dependency -- it is already used by the contact quadrature.

"""
    RitzBasis(l, K)

Radial trial functions for mode `l`: `phi_k(x) = x^(l+1+2(k-1))`, `k = 1..K`.

The factor `x^(l+1)` builds in regularity at the origin, which is what the model
requires of `psi_l`, so no boundary condition has to be imposed there. `phi_1` is
the potential-flow profile, so `K = 1` reproduces the inviscid limit exactly and
larger `K` adds interior structure. Even increments keep every member regular.
"""
struct RitzBasis
    l::Int
    K::Int
end

npow(b::RitzBasis, k::Int) = b.l + 1 + 2 * (k - 1)
phi(b::RitzBasis, k::Int, x::Real) = x^npow(b, k)
dphi(b::RitzBasis, k::Int, x::Real) = (n = npow(b, k); n * x^(n - 1))
d2phi(b::RitzBasis, k::Int, x::Real) = (n = npow(b, k); n * (n - 1) * x^(n - 2))

"""Legendre `P_l(mu)`, and the theta-derivatives the strain components need."""
function legendre_angular(l::Int, mu::Float64)
    p0, p1 = 1.0, mu
    if l == 0
        P, dPdmu = 1.0, 0.0
    elseif l == 1
        P, dPdmu = mu, 1.0
    else
        for n in 1:(l - 1)
            p0, p1 = p1, ((2n + 1) * mu * p1 - n * p0) / (n + 1)
        end
        P = p1
        dPdmu = l * (mu * p1 - p0) / (mu^2 - 1)
    end
    # Legendre's equation supplies the second derivative without a second recurrence
    d2Pdmu = (2mu * dPdmu - l * (l + 1) * P) / (1 - mu^2)
    s = sqrt(max(1 - mu^2, 0.0))
    dPdth = -s * dPdmu                        # d/dtheta
    d2Pdth = -mu * dPdmu + s^2 * d2Pdmu       # d2/dtheta2
    (P = P, dPdth = dPdth, d2Pdth = d2Pdth, sinth = s, mu = mu)
end

"""
Strain and velocity components of the field generated by `psi = f(x) C_l(theta)`,
from their analytic modal forms. Returns `(u_r, u_th, e_rr, e_tt, e_pp, e_rt)`.
"""
function modal_field(l::Int, f::Real, df::Real, d2f::Real, x::Real, A)
    L = l * (l + 1)
    u_r = f / x^2 * A.P
    u_th = df / (x * L) * A.dPdth
    e_rr = (df / x^2 - 2f / x^3) * A.P
    e_tt = df / (x^2 * L) * A.d2Pdth + f / x^3 * A.P
    cot_th = A.sinth > 1e-12 ? A.mu / A.sinth : 0.0
    e_pp = f / x^3 * A.P + df / (x^2 * L) * cot_th * A.dPdth
    T_op = d2f - 2df / x + L * f / x^2          # the tangential-stress operator
    e_rt = T_op / (2 * x * L) * A.dPdth
    (u_r, u_th, e_rr, e_tt, e_pp, e_rt)
end

"""
    assemble(b::RitzBasis, Oh; eta = (x, mu) -> 1.0, nx = 40, nmu = 40)

The three matrices of the variational statement, for one surface mode.

`eta` is the viscosity field in units of the zero-shear plateau, evaluated at
`(x, mu)`. For a Newtonian fluid it is `1`; for a generalized Newtonian one it is
`eta(gammadot)` on the current state, which makes `K` state-dependent.
"""
function assemble(b::RitzBasis, Oh::Real; eta = (x, mu) -> 1.0,
                  nx::Int = 40, nmu::Int = 40)
    l, K = b.l, b.K
    xs, wxs = gauss_legendre_nodes(nx, 0.0, 1.0)
    mus, wmus = gauss_legendre_nodes(nmu, -1.0, 1.0)
    M = zeros(K, K)
    Kd = zeros(K, K)
    for (x, wx) in zip(xs, wxs), (mu, wmu) in zip(mus, wmus)
        A = legendre_angular(l, mu)
        w = wx * wmu * 2pi * x^2                     # dV = 2 pi x^2 dx dmu
        ev = eta(x, mu)
        F = ntuple(k -> modal_field(l, phi(b, k, x), dphi(b, k, x),
                                    d2phi(b, k, x), x, A), K)
        for a in 1:K, c in a:K
            Fa, Fc = F[a], F[c]
            M[a, c] += w * (Fa[1] * Fc[1] + Fa[2] * Fc[2])
            Kd[a, c] += w * 2 * ev * (Fa[3] * Fc[3] + Fa[4] * Fc[4] +
                                      Fa[5] * Fc[5] + 2 * Fa[6] * Fc[6])
        end
    end
    for a in 1:K, c in 1:a-1        # both forms are Hessians, hence symmetric
        M[a, c] = M[c, a]; Kd[a, c] = Kd[c, a]
    end
    Kd .*= Oh
    # surface energy: rank one, seeing the interior only through the trace at x = 1
    tr = [phi(b, k, 1.0) for k in 1:K]
    G = (4pi / (2l + 1)) * (l - 1) * (l + 2) * (tr * tr')
    (M = M, C = Kd, G = G)
end

"""
    decay_rates(b::RitzBasis, Oh; kwargs...) -> Vector{ComplexF64}

Returns `(sigma, cond_M)`: roots of the quadratic eigenvalue problem `(sigma^2 M - sigma C + G) a = 0`,
i.e. the free-decay rates of mode `l` for `chi ~ exp(-sigma t)`.

Linearised to a standard generalized eigenproblem of twice the size. The physical
root is the one with the smallest real part -- the least damped.
"""
function decay_rates(b::RitzBasis, Oh::Real; kwargs...)
    F = assemble(b, Oh; kwargs...)
    K = b.K
    # WHITEN by the Cholesky factor of M before linearising. The monomial trial
    # functions are Vandermonde-like, so M's condition number grows fast with K and
    # the raw pencil returns spurious near-zero roots: at K = 8 omega^2 collapses to
    # 1e-9 and lambda halves, silently, while K = 5 is accurate to 1e-11. Whitening
    # moves the usable range out; it does not make the basis good, and `cond_M` is
    # returned so a caller can see when it has run out of room.
    Lc = cholesky(Symmetric(F.M)).L
    Ci = Lc \ (F.C / Lc')
    Gi = Lc \ (F.G / Lc')
    # [sigma^2 I - sigma Ci + Gi] y = 0  linearised:
    Abig = [Ci  -Gi; Matrix(I, K, K)  zeros(K, K)]
    Bbig = Matrix(I, 2K, 2K)
    (sigma = eigvals(Abig, Bbig), cond_M = cond(F.M))
end

"""
    dominant_pair(b::RitzBasis, Oh; kwargs...) -> (lambda, omega2)

The least-damped root pair, in the convention the Newtonian literature uses:
`zeta.. + 2 lambda zeta. + omega^2 zeta = 0`, returning `(lambda, omega^2)`.
Comparable directly against `reid_lambda_omega2`.

Note which `omega^2` this is. For that oscillator the roots are
`sigma = lambda +- i sqrt(omega^2 - lambda^2)`, so by Vieta `omega^2` is their
PRODUCT, `|sigma|^2` -- not `Im(sigma)^2`, which is the damped frequency
`omega^2 - lambda^2`. Reporting the latter leaves a discrepancy against Reid of
exactly `lambda^2/omega^2` that does not shrink as the basis is refined: a plateau
at `6.1e-3` for `Oh = 0.05` and `1.6e-1` for `Oh = 0.3`, while `lambda` itself was
converging to machine precision. A convergence study is what exposes a convention
error of this kind, because a wrong convention converges to the wrong number.
"""
function dominant_pair(b::RitzBasis, Oh::Real; kwargs...)
    R = decay_rates(b, Oh; kwargs...)
    σ = R.sigma
    finite = filter(s -> isfinite(s) && real(s) > 1e-12, σ)
    length(finite) < 2 && return (NaN, NaN)
    # VIETA ON THE TWO SLOWEST ROOTS, which is what lambda and omega^2 are. For an
    # underdamped mode those two are a conjugate pair and this reduces to
    # (Re sigma, |sigma|^2); above the critical Ohnesorge the pair goes REAL and the
    # conjugate reading breaks -- at Oh = 1, l = 2 it is wrong by 64%, and no amount
    # of basis refinement helps, because the two roots are then different numbers.
    # Taking the two slowest and applying Vieta covers both regimes.
    idx = partialsortperm(real.(finite), 1:2)
    s1, s2 = finite[idx[1]], finite[idx[2]]
    (real(s1 + s2) / 2, real(s1 * s2))
end
