# The Thenarianto et al. (2023) rebound data, one figure per surface.
#
# Experiment only: no model, no fit. This is the dataset laid out so that what it
# contains can be seen before anything is compared against it.
#
# Each surface carries two droplet populations, generated by different means and
# spanning different sizes, so they are drawn differently rather than pooled:
#
#   filled   millimetre drops, R ~ 1.1-1.5 mm, dispensed from a syringe
#   hollow   submillimetre drops, R ~ 20-480 um, sprayed
#
# Restitution of exactly zero is a measurement, not a gap: below a critical Weber
# number the drop does not leave the surface at all. Those points are plotted where
# they belong, on the axis.
#
#   julia --project=docs scripts/figure_thenarianto.jl
#
# Writes outputs/figures/figure_thenarianto_glaco.png and _bsi.png.

using Printf, Statistics
using Plots
gr()

const ROOT = joinpath(@__DIR__, "..")
const FIGS = joinpath(ROOT, "outputs", "figures")
mkpath(FIGS)

## Where the two populations separate. The gap is wide -- Glaco jumps from 0.48 mm
## to 1.28 mm with nothing between -- so the threshold is not a judgement call.
const R_SPLIT = 0.8e-3   # m

const SURFACES = [
    (key = "glaco", csv = "glaco_restitution.csv", title = "Glaco coating"),
    (key = "bsi",   csv = "bsi_restitution.csv",   title = "Black silicon"),
]

function read_data(csv)
    We, C, Oh, Bo, R = Float64[], Float64[], Float64[], Float64[], Float64[]
    for ln in eachline(joinpath(ROOT, "data", csv))
        (startswith(ln, "#") || startswith(ln, "We")) && continue
        v = parse.(Float64, split(strip(ln), ','))
        push!(We, v[1]); push!(C, v[2]); push!(Oh, v[3]); push!(Bo, v[4]); push!(R, v[5])
    end
    (; We, C, Oh, Bo, R)
end

function figure(s)
    d = read_data(s.csv)
    big = d.R .>= R_SPLIT
    sml = .!big

    ttl = @sprintf("%s  —  Oh %.4f–%.4f,  Bo %.1e–%.2f",
                   s.title, minimum(d.Oh), maximum(d.Oh), minimum(d.Bo), maximum(d.Bo))

    ## Explicit decade ticks: the data spans nearly six decades and the default
    ## picks two, which makes the horizontal position of anything unreadable.
    lo, hi = floor(Int, log10(minimum(d.We))), ceil(Int, log10(maximum(d.We)))
    tks = [10.0^k for k in lo:hi]
    xl = (10.0^(log10(minimum(d.We)) - 0.25), 10.0^(log10(maximum(d.We)) + 0.25))
    plt = plot(xscale = :log10, xlabel = "Weber number  We", ylabel = "restitution  ε",
               xticks = tks, xlims = xl,
               title = ttl, titlefontsize = 11,
               size = (900, 620), dpi = 200, framestyle = :axes, grid = false,
               legend = :bottomright, legendfontsize = 10,
               guidefontsize = 13, tickfontsize = 12,
               ylims = (0, 1), foreground_color_axis = :gray40,
               foreground_color_border = :gray40,
               left_margin = 8Plots.mm, bottom_margin = 8Plots.mm,
               right_margin = 5Plots.mm, top_margin = 5Plots.mm)

    ## Hollow for the sprayed submillimetre drops, filled for the dispensed
    ## millimetre ones: same quantity, different experiment.
    scatter!(plt, d.We[sml], d.C[sml];
             mc = :white, msc = :steelblue, msw = 1.4, ms = 5.5,
             label = @sprintf("R = %.3f–%.3f mm  (n = %d)",
                              1000minimum(d.R[sml]), 1000maximum(d.R[sml]), sum(sml)))
    scatter!(plt, d.We[big], d.C[big];
             mc = :indianred, msc = :indianred, msw = 0, ms = 5.5, alpha = 0.85,
             label = @sprintf("R = %.2f–%.2f mm  (n = %d)",
                              1000minimum(d.R[big]), 1000maximum(d.R[big]), sum(big)))

    out = joinpath(FIGS, "figure_thenarianto_$(s.key).png")
    savefig(plt, out)
    @printf("%-14s n = %3d  (%d large, %d small)  We %.1e–%.1f  ε %.2f–%.2f  zeros %d\n",
            s.title, length(d.We), sum(big), sum(sml),
            minimum(d.We), maximum(d.We), minimum(d.C), maximum(d.C), count(==(0.0), d.C))
    println("  wrote ", out)
end

foreach(figure, SURFACES)
